// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.cjs
require('dotenv').config(); // Garante que o Node leia o seu arquivo .env
const { defineConfig, env } = require('prisma/config');

module.exports = defineConfig({
  schema: './prisma/schema.prisma', // Passando o caminho direto como String
  datasource: {
    url: env('DATABASE_URL'), // Usa o auxiliar nativo do Prisma 7
  },
});